### ISSUE TITLE
No more WUServer on lastest windows

### ISSUE THREAD

**Issue by ICT-000** [GoSecure/pywsus#11]
Windows update now uses domain download.windowsupdate.com for xmls and au.download.windowsupdate.com for recieving files and IP always changes on almost every request its different, source port also changes always and destination port is always 80. Could this still be used with MITM in this case, any directions how to do it for latest windows 10. Is this WUServer compatibile with latest windows?

**Comment by obilodeau** [comment]
PyWSUS is used to MITM an internally deployed Windows Server Update Services (WSUS) environment. Thus the WSUS in the name. This is Microsoft lingo to say Windows updates served locally and not served directly from Microsoft. The tool is not meant to tamper with Windows Update services outside of WSUS.

**Comment by obilodeau** [comment]
I'm closing this issue but please feel free to open a new issue with more details if you believe that your findings apply to WSUS and not Windows Update Services in general.
